### PR TITLE
Subscriptions page initial UI

### PR DESCRIPTION
**Pull request by scottmai**
Main UI for the subscriptions page except for a couple things. TODO:
- API integration (backend looks broken?)
- A better email input experience (low priority tbh)
- Edit functionality
- Show which notification types are enabled

https://user-images.githubusercontent.com/42781446/190985986-1051a34d-a6fe-47fa-bbb8-8b71aab84fd1.mp4

also added a .jsconfig file that should make a huge difference in developer experience sry for not adding it sooner guys x3

### CODE REVIEW

**Review by beatricehahn — APPROVED** [review]
Looks good, simple and clean

**Review by milkcee12 — APPROVED** [review]
Looks good! :)

**Comment by milkcee12** [comment]
> Looks good! :)

Originally we had the login be a modal that popped up when you hit the bell button and then transition to a tablet, but this works as well

**Comment by scottmai** [comment]
> > Looks good! :)
> 
> Originally we had the login be a modal that popped up when you hit the bell button and then transition to a tablet, but this works as well

Yeah we can still go ahead and add that, i mostly wanted to make sure the logic here was in place.

**Pull request merged**
