### PR TITLE
Responsive layout design

### PR DESCRIPTION
**Pull request by milkcee12**
With the exception of the navbar, the main content is all bootstrapped and responsive!!!

Desktop:
image

Tablet: 
image

Mobile:
image

### CODE REVIEW

**Review by scottmai — APPROVED** [review]
amazing love it thx

**Comment by scottmai** [comment]
Not going to block merge for this, but I noticed that resizing the window causes the app to basically freeze. Here's a screen recording from my pretty fast desktop pc

We don't have to prioritize fixing this since most ppl won't resize, but its kind of interesting



https://user-images.githubusercontent.com/42781446/190935348-3a07f26c-cec0-4aad-9218-8d9324940b93.mp4

**Comment by scottmai** [comment]
Merged this to get the changes into master. Thanks!!!

**Comment by milkcee12** [comment]
> Not going to block merge for this, but I noticed that resizing the window causes the app to basically freeze. Here's a screen recording from my pretty fast desktop pc
> 
> We don't have to prioritize fixing this since most ppl won't resize, but its kind of interesting
> 
>  React.App.-.Google.Chrome.2022-09-18.17-48-26.mp4

Hmm I don't get the freezing problem when I test on my computer---but then again I use Microsoft Edge lol.

**Pull request merged**
